### ISSUE TITLE
Clean up incorrect quotation marks in the manuals

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm-test#1781]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1781*

---
For some reason, trying to make quotes in the documentation like ``this'' doesn't work. It shows up online exactly like that, but it's used throughout all the manuals.

**Comment by pplimport** [comment]
*Original author: Jim Phillips*
*Original date: 2018-01-30 19:53:30*

---
What software is generating the online manuals from LaTeX (and doesn't know how to handle quotes)?

**Comment by stwhite91** [comment]
This is no longer an issue in the rst version of the manual
